import { randomBytes } from "node:crypto";
import { access, writeFile } from "node:fs/promises";
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";

const outputPath = process.env.LIVE_ENV_FILE ?? ".env.live";
const force = process.argv.includes("--force");
const chainId = Number(process.env.LIVE_CHAIN_ID ?? "11155111");
const networkName = process.env.LIVE_NETWORK_NAME ?? "sepolia";
const rpcUrl = process.env.LIVE_RPC_URL ?? "https://replace-with-your-sepolia-rpc";
const relayerUrl = process.env.LIVE_RELAYER_URL ?? "https://relayer.testnet.zama.org/v2";
const relayerApiKey = process.env.LIVE_RELAYER_API_KEY;

async function pathExists(path: string): Promise<boolean> {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
}

function envLine(key: string, value: string): string {
  return `${key}=${value}`;
}

if (!force && (await pathExists(outputPath))) {
  throw new Error(`${outputPath} already exists. Move it or rerun with --force.`);
}

const ownerPrivateKey = generatePrivateKey();
const indexerPrivateKey = generatePrivateKey();
const owner = privateKeyToAccount(ownerPrivateKey);
const indexer = privateKeyToAccount(indexerPrivateKey);
const adminApiKey = randomBytes(24).toString("hex");
const indexerPrivateKeyEnv = `INDEXER_SIGNER_PRIVATE_KEY_${chainId}`;
const network = {
  chainId,
  name: networkName,
  rpcUrl,
  relayerUrl,
  indexerSignerPrivateKeyEnv: indexerPrivateKeyEnv,
  tokens: [],
  ...(relayerApiKey ? { relayerApiKeyEnv: "RELAYER_API_KEY" } : {}),
};
const networks = [network];

const content = [
  "# Generated by pnpm live:accounts. Do not commit.",
  envLine("DATABASE_URL", "postgres://indexer:indexer@localhost:5432/confidential_indexer"),
  envLine(
    "HYPERINDEX_DATABASE_URL",
    "postgres://indexer:indexer@localhost:5432/confidential_indexer",
  ),
  envLine("ADMIN_API_KEY", adminApiKey),
  envLine("API_HOST", "127.0.0.1"),
  envLine("API_PORT", "3000"),
  envLine("EVENT_SOURCE_POLL_LIMIT", "100"),
  envLine("WORKER_INTERVAL_MS", "2000"),
  envLine("CHAIN_ID", String(chainId)),
  envLine("NETWORK_NAME", networkName),
  envLine("RPC_URL", rpcUrl),
  envLine("RELAYER_URL", relayerUrl),
  envLine("RELAYER_API_KEY", relayerApiKey ?? ""),
  envLine("OWNER_PRIVATE_KEY", ownerPrivateKey),
  envLine("OWNER_ADDRESS", owner.address),
  envLine(indexerPrivateKeyEnv, indexerPrivateKey),
  envLine("INDEXER_SIGNER_ADDRESS", indexer.address),
  envLine("INITIAL_SUPPLY", "1000"),
  envLine("TRANSFER_AMOUNT", "25"),
  envLine("TOKEN_ADDRESS", ""),
  envLine("START_BLOCK", "0"),
  envLine("NETWORKS_JSON", JSON.stringify(networks)),
  "",
].join("\n");

await writeFile(outputPath, content, { mode: 0o600 });
console.log(
  JSON.stringify(
    {
      envFile: outputPath,
      chainId,
      ownerAddress: owner.address,
      indexerSignerAddress: indexer.address,
      next: "Fund ownerAddress, set RPC_URL, optionally set RELAYER_API_KEY, then run pnpm live:deploy.",
    },
    null,
    2,
  ),
);
